### ISSUE TITLE
[Table] Add ability to make right column "sticky"

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#361]
Currently, we can stick a column at left side of the table by doing:

```css
.table :deep(.col-name) {
  --table-col-position: sticky;
  --table-col-z-index: 50;
}
```

This only works for sticking the column on left side because:

1. There is no option to set position `right` on `<STableItem>`.
2. Left border disappears when scrolling since table cell only has border on right side.

We need to find a way to fix the above to enable right side sticky position.
