### ISSUE TITLE
[Table] Add a way to apply `font-feature-settings` css class to `text` cell

### ISSUE THREAD

**Issue by kiaking** [globalbrain/sefirot#506]
There are cases when I want to specify `font-feature-settings` to text cell. For example, when we have padded ID listed in the table. e.g.:

- ID-0000001
- ID-0000002
- ID-0000003
- ...

By setting `font-feature-settings: "tnum"`, we can make these numbers aligned.

Maybe add css variable like `--table-cell-font-feature-settings`?

```css
/* Specify in component */
:deep(.table) {
  --table-col-width: 128px;
  --table-cell-font-feature-settings: "tnum";
}
```

**Comment by brc-dd** [comment]
how is it different from just specifying:

```css
:deep(.table) {
  font-feature-settings: "tnum"
}
```

**Comment by kiaking** [comment]
Ah sorry my example was bad. I want certain cell only. But wait, would this work? I mean `font-feature-settings` will always be inherited? I wanted to actually do this.

```css
.table :deep(.col-id) {
  font-feature-settings: "tnum";
}
```
